// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using a.Server.Data;

#nullable disable

namespace a.Server.Migrations
{
    [DbContext(typeof(DataContext))]
    [Migration("20230209123451_a1")]
    partial class a1
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("a.Shared.Product", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ImageUrl")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Price")
                        .HasColumnType("int");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Products");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Description = "بروید ای حریفان بکشید یار ما را . به من آورید آخر صنم گریز پا رادم سخت گرم دارد که به جادوی و افسون . بزند گره بر آب او و ببند او هوا ر ا ",
                            ImageUrl = "./img/a.jpg",
                            Price = 11,
                            Title = "بکشید یار ما را"
                        },
                        new
                        {
                            Id = 2,
                            Description = "به ترانه های شیرین به بهانه های زرین . بکشید سوی خانه مه خوب خوش لقا را",
                            ImageUrl = "./img/b.jpg",
                            Price = 33,
                            Title = "به ترانه های شیرین"
                        },
                        new
                        {
                            Id = 3,
                            Description = "وگر او به وعده گوید که دمی دگر بیایم . همه وعده مکر باشد بفریبد او شما را",
                            ImageUrl = "./img/c.jpg",
                            Price = 3,
                            Title = "دمی دگر"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
